### ISSUE TITLE
Registration is skiped on rhel7.5 because subscription_manager_registered cap no longer works

### ISSUE THREAD

**Issue by asouini** [projectatomic/adb-vagrant-registration#126]
`subscription-manager list --consumed` no longer returns **_No consumed subscription pools to list_** in _rhel7.5_ but **_No consumed subscription pools were found_** instead. they changed the text output.

maybe try something else https://github.com/projectatomic/adb-vagrant-registration/blob/f41efa361b52368a4c2a929b48c20127fc293982/plugins/guests/redhat/cap/subscription_manager.rb#L7

replacing it with this works for me now `subscription-manager list --consumed --pool-only | grep -E '^[a-f0-9]{32}$'`

**Comment by lmayorga1980** [comment]
@Poohblah Thank you!!!
![screenshot from 2018-07-24 09-00-42](https://user-images.githubusercontent.com/3172378/43139582-1fe2d8f4-8f20-11e8-90b9-6bdc6a54c65c.png)

**Comment by ktreese** [comment]
Hello!  I ran into this issue recently and fortunately came across this workaround.  Are there any plans to release this fix soon?  Thanks!

**Comment by Poohblah** [comment]
None that I'm aware of.  My coworkers and I have spent a little time searching for alternatives since this project seems to be abandoned and in need of some TLC, but no luck so far.  Forking sounds more and more appealing every day.

Out of curiosity, do you have a link to the documentation that mentions this plugin?

**Comment by ktreese** [comment]
Here it is.

[CHAPTER 4. USING VAGRANT CONTAINER DEVELOPMENT KIT PLUGINS](https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/2.1/html/getting_started_guide/using-vagrant-plugins#using_the_vagrant_registration_plugin)

Also, at the bottom of that link, this project is linked to in the Additional Resources section.

**Comment by voxik** [comment]
@whitel, @LalatenduMohanty Shouldn't this project be maintained, officially deprecated or transferred to somebody, who will take care?

**Comment by LalatenduMohanty** [comment]
@voxik I am not able to maintain this project due to lack of time and willing to transfer the ownership to anyone willing to maintain this.
