### ISSUE TITLE
Looking for maintainers for this project

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-vagrant-registration#131]
Due to change in my current work and lack of time, I am not able to maintain this project. So I am willing to give the commit access to anyone who can maintain this project. Please add a comment if you are willing to maintain this project.

**Comment by ktreese** [comment]
I am not a ruby developer, but if nobody volunteers, I'll take it as it would be a shame to have this abandoned.

**Comment by seth-reeser** [comment]
Hi @LalatenduMohanty, I'm with DevOps Group and we manage several vagrant plugins now and are interested to see this project maintained. Are there any significant changes in the RHN subscription model that require rework of this plugin now or in the future that you're aware of? Thanks!

**Comment by haxorof** [comment]
Any ETA on when to expect this plugin to be handed over to new maintainers? Would have been great to get these outstanding pull requests to be merged as soon as possible.

**Comment by seth-reeser** [comment]
> Hi @LalatenduMohanty, I'm with DevOps Group and we manage several vagrant plugins now and are interested to see this project maintained. Are there any significant changes in the RHN subscription model that require rework of this plugin now or in the future that you're aware of? Thanks!

Bump @LalatenduMohanty

**Comment by whitel** [comment]
@seth-reeser as the original author of this project, I would like to see it be maintained as well. I'll try and grab @LalatenduMohanty tomorrow and see if he has any concerns.

To the best of my knowledge this should work with all current versions of sub-man (including rhel8). The biggest challenge I ran in to was identifying rpm-ostree-style systems (which you can't use yum to install on) but i think that is mostly identifiable in the /etc/os-release now.

**Comment by LalatenduMohanty** [comment]
Sorry for the late reply (somehow missed  the old comments). I will be happy to handover this to @seth-reeser.

**Comment by LalatenduMohanty** [comment]
@whitel Can you please give @seth-reeser write access? Looks like I do not have admin access anymore?

**Comment by seth-reeser** [comment]
Thanks, guys. I'll also need push access to https://rubygems.org/gems/vagrant-registration/ my RubyGems user is https://rubygems.org/profiles/sethreeser

`gem owner vagrant-registration -a seth.reeser@devopsgroup.com`

http://guides.rubygems.org/command-reference/#gem-owner

**Comment by whitel** [comment]
@seth-reeser ok, you should have an invite to the github repo and I added you as an owner to the gem. Once you confirm, please close this ticket (which will also test the perms :) )

**Comment by rbywater** [comment]
@seth-reeser / @LalatenduMohanty / @whitel Just wondering if there is any update about swapping maintainership over? https://github.com/projectatomic/adb-vagrant-registration/pull/127 is quite a major showstopper and the fix in the PR works so would be really good to have an official build :)

**Comment by seth-reeser** [comment]
@whitel - apologies for the delay - busy summer :) I have appropriate RubyGems access, but it looks like I need elevated GitHub perms. I'm unable to close this nor have write access.

**Comment by devantoine** [comment]
@LalatenduMohanty can we have an update on this please? 
This project needs a maintainer and there's already some useful PR waiting to be merged.

**Comment by whitel** [comment]
OK, invited @seth-reeser ; sorry for the lag, trying to get permissions sorted out.

**Comment by LalatenduMohanty** [comment]
@seth-reeser Let us know if you have the access now. Sorry for the delay. I would be happy to add more maintainers  for this project. So let us know.

**Comment by seth-reeser** [comment]
All set! Thanks all! We'll dig into the pending pull requests and get moving.
