### ISSUE TITLE
RFE - support for --activationkey

### ISSUE THREAD

**Issue by lukaszachy** [projectatomic/adb-vagrant-registration#29]
I'd like to be able to register the machine using activation key.
To be able to do so I have to be able to set ORG_KEY and ACTIVATION_KEY parameters and registration plugin should run 
'sudo subscription-manager register --org=ORG_KEY --activationkey=ACTIVATION_KEY --auto-attach'

**Comment by strzibny** [comment]
Done in https://github.com/projectatomic/adb-vagrant-registration/commit/50f0b3444d6ed3a126d15c4de1d274783f6b2243.
