### ISSUE TITLE
Use registration plugin in Oh-My-Vagrant

### ISSUE THREAD

**Issue by purpleidea** [projectatomic/adb-vagrant-registration#30]
Finally got my recognition in https://github.com/projectatomic/adb-vagrant-registration/commit/bec4e9e694a868a5ab8a52e69e51fcd113678c8b -- I just saw this by accident today, so I guess it was rolled in quietly, but thanks to @whitel for finally doing the right thing!

In any case, now that that's out of the way, if someone is interested in patching https://github.com/purpleidea/oh-my-vagrant so it can use this plugin, please do! AFAICT, the biggest missing feature is getting the password from a file, instead of having to hardcode it into vagrant. Perhaps this might be a useful design/feature for vagrant-registration?

Please have a look, and if you like, and as long as it's feature complete, then it would probably make sense to avoid having two different methods to do vagrant registration.

If nobody is interested in doing this feature, please feel free to LMK and close the ticket, since from oh-my-vagrant's perspective, subscription manager is already working perfectly.

Cheers,
James

**Comment by strzibny** [comment]
This should be an issue for Oh-My-Vagrant in its own issue tracker, not here, so closing.
