### ISSUE TITLE
Multiple machines require multiple creds

### ISSUE THREAD

**Issue by whitel** [projectatomic/adb-vagrant-registration#32]
While it seems to be an ok feature to allow for multiple machines to have different credentials, if there are global credentials and no per machine credentials, the global credentials should be used.

**Comment by dustymabe** [comment]
Meaning.. you should be able to do this:
```
Vagrant.configure(2) do |config|
  config.registration.username = ENV['SUB_USERNAME'] 
  config.registration.password = ENV['SUB_PASSWORD'] 
  config.vm.define :target do | target |
    target.vm.box = "boxname"
  end
  config.vm.define :target1 do | target1 |
    target1.vm.box = "boxname"
  end
end
```

Rather than having to do this:
```
Vagrant.configure(2) do |config|
  config.vm.define :target do | target |
    target.registration.username = ENV['SUB_USERNAME'] 
    target.registration.password = ENV['SUB_PASSWORD'] 
    target.vm.box = "boxname"
  end
  config.vm.define :target1 do | target1 |
    target1.registration.username = ENV['SUB_USERNAME'] 
    target1.registration.password = ENV['SUB_PASSWORD'] 
    target1.vm.box = "boxname"
  end
end
```

**Comment by strzibny** [comment]
I actually though this works:).

**Comment by humaton** [comment]
I think this was the first approach we have used before. Now it has to be defined per machine.

**Comment by strzibny** [comment]
I see, that's probably the reason I though that merged Vagrantfiles don't work (https://github.com/mitchellh/vagrant/issues/5720).

**Comment by strzibny** [comment]
This is fixed in https://github.com/projectatomic/adb-vagrant-registration/commit/7f81f9ff7975f93016ea57fd635de4b524e30b58, closing.

**Comment by dustymabe** [comment]
Seems to work now. Thanks
