### ISSUE TITLE
Credentials specified via subscriber_username and subscriber_password are silently ignored

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-vagrant-registration#39]
`config.registration.subscriber_username` and `config.registration.subscriber_password` were the configuration entries for passing subscription credentials up to version 0.0.9 of the plugin. Now it is `config.registration.username` and `config.registration.password`. 

Looking at commit #573dd0d206dfacd863fc5fc00f958100dc94a4ff, it seems the intention was to still allow the old keys in order to stay backwards compatible. However, in its latest version 0.0.19 these configuration options get silently ignored. I think they should be accepted or at least a warning should be logged forcing you to change the values.

**Comment by strzibny** [comment]
The design behind the whole change is that we now accept all the values of subscription manager and possibly other managers too (you can make plugins to support SUSE for instance if you want to).

**Comment by hferentschik** [comment]
Sure, but coming from earlier versions of the plugin (as for example 0.0.8 which is shipped with CDK 1), there is no telling why things suddenly not work anymore. All I am saying is that one should at least check whether `config.registration.subscriber_username` was set and if so print an error/warning.

We had now several developers trying to figure out why their credentials were ignored.

**Comment by strzibny** [comment]
@hferentschik Understand, I changed in quite a while ago when I treated the plugin as alpha quality. Now many versions later seems strange to issue a warning like this. I will see if anyone else has an opinion on this.

**Comment by maxandersen** [comment]
+1 on this or at least make the error handling state what is missing. The error is really weird and hard to debug.

**Comment by hferentschik** [comment]
> Understand, I changed in quite a while ago when I treated the plugin as alpha quality. Now many versions later seems strange to issue a warning like this

Yes and no. It is all about expectations. I understand that there are a quite a few versions between 0.0.8 and 0.0.19, but for me this are micro version changes which I would expect to be backwards compatible. But I guess I am biased and always expect some form of semantic versioning - http://semver.org/

But even without semantic versioning, people might be "worried" by something like '0.0.x'. It just does not sound production ready. Maybe time for a 1.0.0 release? But this is all on a tangent.

**Comment by strzibny** [comment]
Actually there is an internal support for what fields are required and if there are not filled in vagrant-registration offers to enter them manually during vagrant up, it just does not tell you used wrong ones. Perhaps it would be a nice addition to support it generally (not just for this use case). I will have a look.

> But even without semantic versioning, people might be "worried" by something like '0.0.x'. It just does not sound production ready. Maybe time for a 1.0.0 release? But this is all on a tangent.

That's why I kept using it, but its true that it is matured enough. I might try to resolve this and then cut a stable 1.0.0.

**Comment by hferentschik** [comment]
> Actually there is an internal support for what fields are required and if there are not filled in vagrant-registration offers to enter them manually during vagrant up, it just does not tell you used wrong ones. Perhaps it would be a nice addition to support it generally (not just for this use case). I will have a look.

Cool

> That's why I kept using it, but its true that it is matured enough. I might try to resolve this and then cut a stable 1.0.0.

+1

**Comment by strzibny** [comment]
@hferentschik 

I implemented something like the following locally:

```
vagrant up
==> default: Domain is not created. Please run `vagrant up` first.
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant-registration_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            1024M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          rhel-7.1
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/vagrant-registration_default.img (40G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
==> default: Registering box with vagrant-registration...
==> default: WARNING: sub_username is not supported for a given subscription manager
==> default: WARNING: sub_password is not supported for a given subscription manager
    default: Would you like to register the system now (default: yes)? [y|n] 
```

Would that work?

**Comment by hferentschik** [comment]
Definitely goes into the right direction :-)

I am wondering whether it should be 

```
WARNING: sub_username is not supported for __any known__ subscription manager
```
or

```
WARNING: sub_username is not supported for __current RHEL__ subscription manager
```

The former would be applicable if you know all properties of the various managers in advance (which you might not) and in the latter 'current' sounds imo better than 'for a given'. If the currently used manager (eg RHEL) could be named would help as well.

Either way, I would start with this line:

```
==> default: WARNING: Unsupported subscription property detected. Please refer to the documentation for a list of supported properties.
```

**Comment by strzibny** [comment]
The thing is that `current` means default `subscription-manager` but we are referring to user specified manager. `any known` is not true either. Your suggested lines would be misleading given a current implementation. I included `for a given manager` because the option might be supported in other managers, just not the one in use.

> Either way, I would start with this line:

It might be better to actually print all supported options directly. I think I will add this and merge.

**Comment by strzibny** [comment]
Okay, I changed it to:

```
==> default: Registering box with vagrant-registration...
==> default: WARNING: i_dont_exist option is not supported for subscription_manager
==> default: subscription_manager supports only the following options:
==> default: skip, unregister_on_halt, username, password, serverurl, baseurl, org, environment, name, auto_attach, activationkey, servicelevel, release, force, type
```

**Comment by hferentschik** [comment]
Looking good. I think this gives enough context information to debug problems. Thanks.

>  if the given manager had a name that would be the best I guess.

that would indeed be nice
