### ISSUE TITLE
User should have more than one try to fill username and password

### ISSUE THREAD

**Issue by optak** [projectatomic/adb-vagrant-registration#44]
If I use registration plugin without saved ceredentials (in Vagrantfile), I have just one try to fill username and password correctly and if I make error, I have to do "vagrant halt && vagrant up".
It would be nice if this plugin support one of this options:
1) allow for example 3 attempts to fill credentials
2) give a hint how to do it manually after "vagrant ssh"

**Comment by strzibny** [comment]
I think it would complicate the current codebase for something that is not used so often, but perhaps we should offer `vagrant (un)register` commands that can be ran anytime user wants. Running them could be then a 'hint' you are talking about.

**Comment by hferentschik** [comment]
Can we add the label focus:devex to this one?
