### ISSUE TITLE
If an error occurs during registration the subscription password is printed clear text

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-vagrant-registration#47]
I got the following error message:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cmd=$(subscription-manager register --username='hferentschik@redhat.com' --password='<this was my cleartext passowrd>' --auto-attach --force); if [ "$?" != "0" ]; then echo $cmd | grep 'This system is already registered' || (echo $cmd 1>&2 && exit 1) ; fi

Stdout from the command:

Stderr from the command:

Invalid username or password. To create a login, please visit https://www.redhat.com/wapps/ugc/register.html
Registering to: subscription.rhn.redhat.com:443/subscription
```

Funny enough the username and password were actually correct, so registration must have failed due to another error.

**Comment by strzibny** [comment]
> Funny enough the username and password were actually correct, so registration must have failed due to another error. 

Error you are facing is directly from `subscription-manager`, vagrant-registration does nothing with it.

Otherwise I know about that. I agree that this would be nice to fix.

**Comment by hferentschik** [comment]
Do you know where one would report this then?

**Comment by strzibny** [comment]
@hferentschik Red Hat's Bugzilla and subscription-manager component. But first log in to the VM and try calling subscription-manager manually...

**Comment by strzibny** [comment]
Fixed in https://github.com/projectatomic/adb-vagrant-registration/pull/50/commits.
