### ISSUE TITLE
vagrant crash without credentials in variables

### ISSUE THREAD

**Issue by optak** [projectatomic/adb-vagrant-registration#48]
If plugin is configured to expect username and password from environment in some variables, (almost) every vagrant command crashes with ruby syntax error.
In this case It can fixed by providing such variables or reconfiguring plugin.
Plugin should check if variables are set and are sane (no syntax error).
I can see no reason to strictly require passing RHN credentials for commands like "vagrant status" or "vagrant halt".

Output:
$ vagrant status
/home/optak/.vagrant.d/gems/gems/vagrant-registration-1.0.0/lib/vagrant-registration/config.rb:26:in `eval': (eval):1: syntax error, unexpected end-of-input (SyntaxError)
@conf.username= 
                ^
	from /home/optak/.vagrant.d/gems/gems/vagrant-registration-1.0.0/lib/vagrant-registration/config.rb:26:in `method_missing'
	from /home/optak/.vagrant.d/Vagrantfile:2:in `block in <top (required)>'
	from /usr/share/vagrant/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /usr/share/vagrant/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /usr/share/vagrant/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /usr/share/vagrant/lib/vagrant/config/loader.rb:97:in `each'
	from /usr/share/vagrant/lib/vagrant/config/loader.rb:97:in `block in load'
	from /usr/share/vagrant/lib/vagrant/config/loader.rb:94:in `each'
	from /usr/share/vagrant/lib/vagrant/config/loader.rb:94:in `load'
	from /usr/share/vagrant/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /usr/share/vagrant/lib/vagrant/environment.rb:691:in `new'
	from /usr/share/vagrant/lib/vagrant/environment.rb:691:in `vagrantfile'
	from /usr/share/vagrant/lib/vagrant/environment.rb:441:in `host'
	from /usr/share/vagrant/lib/vagrant/environment.rb:207:in `block in action_runner'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:33:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:33:in `run'
	from /usr/share/vagrant/lib/vagrant/environment.rb:428:in `hook'
	from /usr/share/vagrant/lib/vagrant/environment.rb:673:in `unload'
	from /usr/share/vagrant/bin/vagrant:177:in `ensure in <main>'
	from /usr/share/vagrant/bin/vagrant:177:in `<main>'

**Comment by strzibny** [comment]
This should now be fixed by https://github.com/pvalena/adb-vagrant-registration/commit/5f544e247391ba776d987d6c6029a7723a107189.
