### ISSUE TITLE
`vagrant destroy` not triggering subscription deactivation and removal

### ISSUE THREAD

**Issue by mattpollard** [projectatomic/adb-vagrant-registration#57]
Hi! I'm not sure if this is an appropriate channel for reporting a problem, but perhaps someone will see it and have an idea about what's going wrong.

For some reason, `destroy` with either `kitchen` or `vagrant` is no longer properly unsubscribing and deregistering Red Hat instances for us. I _think_ it was working prior to Saturday, December 19, but then again, it might just be that I hadn't yet hit our Red Hat developer subscription limit of 100 active units over the week that I'd been using the Red Hat Vagrant box and vagrant-registration plugin.

In any case, here are the versions in use on my MacBook Pro, which is running OS X 10.11.2 (15C50):

- VMware Fusion 8.1.0 (3272237)
- Test Kitchen 1.4.2
- Vagrant 1.8.1
- vagrant-registration 1.1.0
- vagrant-vmware-fusion 4.0.3 (though the problem occurs with the VirtualBox provider, too)
- Official Red Hat Vagrant box beta 3 for VMware Fusion from [Container Development Kit 2](https://access.redhat.com/downloads/content/293/ver=2/rhel---7/2.0.0/x86_64/product-downloads)

I can confirm that when I `kitchen converge` using my Red Hat Vagrant box, my subscription is set up properly. I store my Red Hat credentials in my global `Vagrantfile`. I can verify the subscription with `subscription-manager` after I connect to the instance via SSH, and the instance is listed as consuming a unit of our developer license on Red Hat's [Subscription Units page](https://access.redhat.com/management/consumers).

If I `kitchen destroy` (or `vagrant destroy`), however, my subscription is still consumed when I check the Subscription Units page. My colleague, who's using Red Hat's VirtualBox box from the Container Development Kit, also experiences this problem.

Is this known? Is there some information I can provide so that someone can help out?

Thanks!

**Comment by mattpollard** [comment]
Thanks for your work on this. Looking forward to a solution to the problem, because having to manually unsubscribe and unregister is becoming a pain, and using a workaround like the vagrant-triggers plugin seems like a hack.

I'm really sorry for what's probably a dumb question: is there any way I can take advantage of your fix now? @strzibny, do you plan to do a new release of the plugin soon?

**Comment by strzibny** [comment]
@mattpollard you can always build this gem with `gem build` command and install with `vagrant plugin install`.

We have enough new things/fixes for a new version, so I am up for releasing it.

**Comment by mattpollard** [comment]
I'm happy to build for myself. But yeah, a release would be a huge help for us – that way, the members of my small team don't need to all build individually. We'd appreciate it!
