### ISSUE TITLE
subscription-manager requires privilege escalation

### ISSUE THREAD

**Issue by stephenpc** [projectatomic/adb-vagrant-registration#64]
** INFO config: Evaluating registration configuration: @conf.manager**
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
**DEBUG guest: Searching for cap: subscription_manager**
DEBUG guest: Checking in: redhat
**DEBUG guest: Found cap: subscription_manager in redhat**
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
**DEBUG guest: Searching for cap: subscription_manager
DEBUG guest: Checking in: redhat
DEBUG guest: Found cap: subscription_manager in redhat
 INFO guest: Execute capability: subscription_manager [#<Vagrant::Machine: vagrant-rhel7 (VagrantPlugins::ProviderVirtualBox::Provider)>] (redhat)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: /usr/sbin/subscription-manager (sudo=false)
DEBUG ssh: stderr: Error: this command requires root access to execute**

DEBUG ssh: Exit status: 8
DEBUG register: Registration manager not found on guest
 INFO config: Evaluating registration configuration: @conf.skip
 INFO warden: Calling OUT action: #<VagrantPlugins::Registration::Action::Register:0x000001029453b0>

**Comment by electrofelix** [comment]
I suspect your problem is https://github.com/projectatomic/adb-vagrant-registration/blob/master/plugins/guests/redhat/cap/subscription_manager.rb#L14

Since you were looking for a solution in the irc channel, I figured a temporary workaround such as the following might help if you add it to your Vagrantfile before the config block:
```
module VagrantPlugins
  module GuestRedHat
    module Cap
      class SubscriptionManager
        def self.subscription_manager(machine)
          machine.communicate.test('sudo /usr/sbin/subscription-manager')
        end
      end
    end
  end
end
```

**Comment by stephenpc** [comment]
I'm still seeing the same behavior even after adding that block. Here's my Vagrantfile...

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Require current version of Vagrant
Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|

  config.vm.box = 'boxname'
  config.vm.hostname = 'boxhostname'
  config.vm.box_check_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: false

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '4096'
    vb.cpus = '2'
  end

  module VagrantPlugins
    module GuestRedHat
      module Cap
        class SubscriptionManager
          def self.subscription_manager(machine)
            machine.communicate.test('/usr/sbin/subscription-manager', sudo: true)
          end
        end
      end
    end
  end

  # Vagrant Registration Plugin config for RHEL hosts
  if Vagrant.has_plugin?('vagrant-registration')
    config.registration.serverurl = 'https://satellitehost/rhsm'
    config.registration.ca_cert = './katello-server-ca.crt'
    config.registration.baseurl = 'https://satellitehost/pulp/repos'
    config.registration.org = 'ORGNAME'
    config.registration.activationkey = 'ACTKEY'
  else
    puts 'Vagrant registration plugin not detected.\n'
  end

  # Provision via Ansible
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'vagrant.yml'
    ansible.sudo = true
    ansible.verbose = 'v'
  end

end
```

**Comment by stephenpc** [comment]
Note, the same thing happens when I put that block outside of Vagrant.configure...

**Comment by electrofelix** [comment]
forgot that a require would be needed first:
```require 'vagrant-registration/plugins/guests/redhat/cap/subscription_manager'```

This definitely can be made to work, as I have some patches for the ansible provisioner for our vagrant env that I load in this way.

**Comment by strzibny** [comment]
This is a regression introduced by https://github.com/projectatomic/adb-vagrant-registration/pull/59.

Fixed in https://github.com/projectatomic/adb-vagrant-registration/commit/8b516560eddfbc3ac332bbdef60ffb471c7f28b7.

**Comment by strzibny** [comment]
This is the fixed version: https://github.com/projectatomic/adb-vagrant-registration/releases/tag/v1.2.1. Please update.

**Comment by stephenpc** [comment]
Looks like it's working. Thanks a bunch
