### ISSUE TITLE
vagrant-registration does not work in conjunction with the vagrant-vbguest plugin

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-vagrant-registration#69]
Following up on issue #40 which does not seem to be resolved yet.

Installed vagrant-registration (1.2.1) and vagrant-vbguest (0.11.0) on OS X and Windows 10 and tried to start VM (_Vagrantfile_ as of [openshift-vagrant](https://github.com/redhat-developer-tooling/openshift-vagrant)). In both cases I get:

    $vagrant up
    
        Red Hat subscription credentials are needed for this VM.
        You can supply them interactively or by setting environment variables.
        Set these environment variables to your subscription username/password to avoid     interactive registration:
    
        $ export SUB_USERNAME=rhn-username
        $ export SUB_PASSWORD=password
      
    Bringing machine 'cdk' up with 'virtualbox' provider...
    ==> cdk: Importing base box 'cdk_v2'...
    ==> cdk: Matching MAC address for NAT networking...
    ==> cdk: Setting the name of the VM: openshift.cdk-2
    ==> cdk: Clearing any previously set network interfaces...
    ==> cdk: Preparing network interfaces based on configuration...
        cdk: Adapter 1: nat
        cdk: Adapter 2: hostonly
    ==> cdk: Forwarding ports...
        cdk: 22 => 2222 (adapter 1)
    ==> cdk: Running 'pre-boot' VM customizations...
    ==> cdk: Booting VM...
    ==> cdk: Waiting for machine to boot. This may take a few minutes...
        cdk: SSH address: 127.0.0.1:2222
        cdk: SSH username: vagrant
        cdk: SSH auth method: private key
        cdk: Warning: Connection timeout. Retrying...
        cdk: 
        cdk: Vagrant insecure key detected. Vagrant will automatically replace
        cdk: this with a newly generated keypair for better security.
        cdk: 
        cdk: Inserting generated public key within guest...
        cdk: Removing insecure key from the guest if it's present...
        cdk: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> cdk: Machine booted and ready!
    No installation found.
    Loaded plugins: product-id, search-disabled-repos, subscription-manager
    This system is not registered to Red Hat Subscription Management. You can use     subscription-manager to register.
    There are no enabled repos.
     Run "yum repolist all" to see the repos you have.
     You can enable repos with yum-config-manager --enable <repo>
    ==> cdk: Checking for guest additions in VM...
        cdk: No guest additions were detected on the base box for this VM! Guest
        cdk: additions are required for forwarded ports, shared folders, host only
        cdk: networking, and more. If SSH fails on this machine, please install
        cdk: the guest additions and repackage the box to continue.
        cdk: 
        cdk: This is not an error message; everything may continue to work properly,
        cdk: in which case you may ignore this message.
    ==> cdk: [vagrant-hostsupdater] Checking for host entries
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!
    
    yum install -y kernel-devel-`uname -r` gcc make perl bzip2
    
    Stdout from the command:
    
    Loaded plugins: product-id, search-disabled-repos, subscription-manager
    This system is not registered to Red Hat Subscription Management. You can use     subscription-manager to register.
    
    
    Stderr from the command:
    
    There are no enabled repos.
     Run "yum repolist all" to see the repos you have.
     You can enable repos with yum-config-manager --enable <repo>    

Seems vbguest still runs prior to registration.

**Comment by hferentschik** [comment]
Can we add the focus:devex label and make it a blocker.

**Comment by hferentschik** [comment]
Actually, while the vagrant-vbguest plugin is installed, the vagrant-registration plugin does not run at all. No matter what. Once I uninstall _vbguest_, the registration happens again.

**Comment by hferentschik** [comment]
BTW, I am taking a bit of a look at this. If I find something, I'll post it here ...

**Comment by jgrumboe** [comment]
Did you try it like mentioned here (http://stackoverflow.com/questions/31610801/how-can-i-define-the-run-order-of-vagrant-middleware-plugins) with the trigger.after statements?
I bet u already did but i wanted to ask :)

**Comment by hferentschik** [comment]
I tried, but this is really a workaround in the Vagrantfile. I would like to fix it in the plugin. That said, I think I have a fix. I'll prepare a pull request...

**Comment by hferentschik** [comment]
Here is the pull request - https://github.com/projectatomic/adb-vagrant-registration/pull/70

I added a vagrant-spec acceptance test harness with a bunch of sample acceptance test (including ones for the issue at hand). These tests should be fairly simple to run continuously against a CI server.

**Comment by pvalena** [comment]
Thank you for the PR, I am testing it now.
