### ISSUE TITLE
Release latest version of vagrant-registration

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-vagrant-registration#83]
We have couple of commits post the last release and we should do a release with the current code.

CC @pvalena @hferentschik @budhrg 

Tasks for the release

- [x] Choose a version. may be 1.3.0?

- [x] Run the tests from master on Windows
- [x] Tests on OSX 
- [ ] Tests on RHEL
- [x] Tests on Fedora
- [x] Release the gem

**Comment by pvalena** [comment]
Hi, I have tested current `master`[1] on Fedora 23 with libvirt provider and on OSX with virtualbox provider and vbguest additions - both are without any issues.

I will test Win7 and hopefully more tomorrow.

[1] https://github.com/projectatomic/adb-vagrant-registration/tree/c90d351b1a943a065215e763d26fcc9f5bb39a0e

**Comment by praveenkumar** [comment]
@pvalena Any update you have regarding this?

**Comment by pvalena** [comment]
The tests on windows are ok.

The version should be IMO 1.2.2, as there is only a fix of regression and new test suite released. No features or upgrades.

**Comment by budhrg** [comment]
I have tested master branch with Fedora 23 + virtualbox + without guest edition. It is working fine. [Logs here](https://gist.github.com/budhrg/a844a7ea4e0eea11e158d2f4d36dec23).

**Comment by LalatenduMohanty** [comment]
It works fine with OSX and vagrant-vbguest plugin.
