### ISSUE TITLE
Proxy settings are not applied to all commands

### ISSUE THREAD

**Issue by tripledes** [projectatomic/adb-vagrant-registration#99]
I've checked on unregister and attach, and seems proxy settings are missing on those commands, thus vagrant fails.

I could try to produce a PR but I'd like to know what would be the preferred method for applying them, I think the easiest and cleanest would be to use ```subscription-manager config``` and store the settings so it's not needed to apply them everywhere.

Another option would be to have a method (like others on the plugin) that would return the proxy related settings to be appended to the command being executed.

**Comment by hferentschik** [comment]
I think this is error report is correct. [Here](https://github.com/projectatomic/adb-vagrant-registration/blob/master/plugins/guests/redhat/cap/subscription_manager.rb#L37) the options should be applied in a similar way to [here](https://github.com/projectatomic/adb-vagrant-registration/blob/master/plugins/guests/redhat/cap/subscription_manager.rb#L20).

This slipped through, since the un-register so far did not use any options at all. This needs to be added and tested. 

@tripledes, ooi how does this manifest itself? You mean 'vagrant destroy' or 'vagrant halt' fail? TBH, I never noticed. 

> I could try to produce a PR but I'd like to know what would be the preferred method for applying them, I think the easiest and cleanest would be to use subscription-manager config and store the settings so it's not needed to apply them everywhere.

I thought about this, but going via the generic options way is more aligned with the current implementation.

**Comment by hferentschik** [comment]
@tripledes can you provide a patch or maybe @budhrg can take a look at this?

**Comment by tripledes** [comment]
@hferentschik I noticed it when during the process of bringing the machine up, I noticed some commands were taking way too much time or even worse, failing.

I've got a quick patch for it as I needed it to be working quickly, but I can rework it to match the current implementation:

https://github.com/tripledes/adb-vagrant-registration/commit/96d3adaa38cfabd0c39b8308fbdb350fb08cb983

I'll try to have the new patch ready after the weekend.

**Comment by LalatenduMohanty** [comment]
@hferentschik @tripledes I tried with and it does not work. I need to dig more
```
         def self.subscription_manager_unregister(machine)
-          machine.communicate.sudo('subscription-manager unregister || :')
+          machine.communicate.sudo("subscription-manager unregister #{configuration_to_options(machine.config.registration)}")
         end
```

**Comment by LalatenduMohanty** [comment]
The issue is `unregister` only takes 3 options as mentioned below. So we can not reuse #{configuration_to_options(machine.config.registration) directly

```
$ sudo subscription-manager unregister --help
Usage: subscription-manager unregister [OPTIONS]

Unregister this system from the Customer Portal or another subscription
management service

Options:
  -h, --help            show this help message and exit
  --proxy=PROXY_URL     proxy URL in the form of proxy_hostname:proxy_port
  --proxyuser=PROXY_USER
                        user for HTTP proxy with basic authentication
  --proxypassword=PROXY_PASSWORD
                        password for HTTP proxy with basic authentication
```

**Comment by LalatenduMohanty** [comment]
FIxed the issue in https://github.com/LalatenduMohanty/adb-vagrant-registration/tree/fix-90. I need to add test now.

**Comment by LalatenduMohanty** [comment]
Looks like I can not write an acceptance test as I can not ssh in to the box after vagrant destroy. I have sent the PR at https://github.com/projectatomic/adb-vagrant-registration/pull/104
